package com.example.pokedex.model

enum class SharedPreferencesPokemon(val geracao : Int, val salvo : String, val listaSalva : String) {
    GERACAO_UM(1, "SALVA_PRIMEIRA_GERACAO", "LISTA_PRIMEIRA_SALVA"),
    GERACAO_DOIS(2, "SALVA_SEGUNDA_GERACAO", "LISTA_SEGUNDA_SALVA"),
    GERACAO_TRES(3, "SALVA_TERCEIRA_GERACAO", "LISTA_TERCEIRA_SALVA"),
    GERACAO_QUATRO(4, "SALVA_QUARTA_GERACAO", "LISTA_QUARTA_SALVA"),
    GERACAO_QUINTA(5, "SALVA_QUARTA_GERACAO", "LISTA_QUINTA_SALVA"),
    GERACAO_SEXTA(6, "SALVA_SEXTA_GERACAO", "LISTA_SEXTA_SALVA"),
    GERACAO_SETIMA(7, "SALVA_SETIMA_GERACAO", "LISTA_SETIMA_SALVA"),
    GERACAO_OITAVA(8, "SALVA_OITAVA_GERACAO", "LISTA_OITAVA_SALVA")
}